spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/mvpmailgunre
    url : jdbc:h2:tcp://localhost/~/pp_tou_change_notice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      # show_sql: true
       format_sql: true

logging.level:
  org.hibernate.SQL: error
# org.hibernate.type: trace